spring:
  application:
    name: CONFIG-SERVER-GIT

eureka:
 client:
   register-with-eureka: true
   fetch-registry: true
   service-url:
     defaultZone: http://localhost:8761/eureka/
   instance:
    hostname: localhost
